// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDWxWChdi4CZZ1tlrdsYwAWlfSXLONZQ',
    appId: '1:566712823231:web:d7d50182c9e36ebeb7850a',
    messagingSenderId: '566712823231',
    projectId: 'aemove-2aea7',
    authDomain: 'aemove-2aea7.firebaseapp.com',
    storageBucket: 'aemove-2aea7.firebasestorage.app',
    measurementId: 'G-CZZ0YRQXYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehQFK9QFPpAg1ilipxBK7sLzioU_W_N8',
    appId: '1:566712823231:android:05ed89ae0c82ea93b7850a',
    messagingSenderId: '566712823231',
    projectId: 'aemove-2aea7',
    storageBucket: 'aemove-2aea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9K3xezdn947GDh21crPzZx9Orf3gSjZI',
    appId: '1:566712823231:ios:a6b776322562ddacb7850a',
    messagingSenderId: '566712823231',
    projectId: 'aemove-2aea7',
    storageBucket: 'aemove-2aea7.firebasestorage.app',
    iosBundleId: 'com.example.aemove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9K3xezdn947GDh21crPzZx9Orf3gSjZI',
    appId: '1:566712823231:ios:a6b776322562ddacb7850a',
    messagingSenderId: '566712823231',
    projectId: 'aemove-2aea7',
    storageBucket: 'aemove-2aea7.firebasestorage.app',
    iosBundleId: 'com.example.aemove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzDWxWChdi4CZZ1tlrdsYwAWlfSXLONZQ',
    appId: '1:566712823231:web:f9b10e2b19924cc5b7850a',
    messagingSenderId: '566712823231',
    projectId: 'aemove-2aea7',
    authDomain: 'aemove-2aea7.firebaseapp.com',
    storageBucket: 'aemove-2aea7.firebasestorage.app',
    measurementId: 'G-SMZTFG87HT',
  );
}
